name: API CI/CD

on:
  push:
    branches:
      - kmilton1/Assignment3
  pull_request:
    branches:
      - kmilton1/Assignment3

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./Potion.Ledger/api/PotionLedger.Api/PotionLedger.Api.csproj

      - name: Test
        run: dotnet test ./Potion.Ledger/api/PotionLedger.Api.Tests/PotionLedger.Api.Tests.csproj -c Release

      - name: Publish
        run: dotnet publish ./Potion.Ledger/api/PotionLedger.Api/PotionLedger.Api.csproj -c Release -o ./api_publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./api_publish
