name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Assignment1
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Assignment1

jobs:
  ci_job:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: Wordle.Web
      - run: npm run test -- --run
        working-directory: Wordle.Web
      - run: npm run build
        working-directory: Wordle.Web

  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: Wordle.Web
      - run: npm run test -- --run
        working-directory: Wordle.Web
      - run: npm run build
        working-directory: Wordle.Web

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FOREST_08E569210 }}
          action: upload
          app_location: Wordle.Web
          output_location: .output/public
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FOREST_08E569210 }}
          action: close
